In [ ]:
# Importing Packages
import numpy as np
import keras
from keras.models import Sequential
from keras.layers import Dense
from sklearn import datasets

In [ ]:
# Loading Dataset
data = datasets.load_iris()
print(data)

{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
     

In [ ]:
x = data.data
y = data.target
z = data.target_names
print(data.feature_names)
print(x[0])

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
[5.1 3.5 1.4 0.2]


In [ ]:
# Split Dataset
from sklearn.model_selection import train_test_split
x_train, x_test,  y_train, y_test = train_test_split(x, y, test_size=0.3)

In [ ]:
# Data Shape
print(x_train.shape)
print(x_test.shape)

(105, 4)
(45, 4)


In [ ]:
# Building the Model
model= Sequential()
model.add(Dense(50,input_shape=(4,), activation="relu"))
model.add(Dense(3, activation='softmax'))

In [ ]:
# Compile the Model
model.compile(optimizer="adam", loss="sparse_categorical_crossentropy", metrics=["accuracy"])

In [ ]:
# Fit the Model
model.fit(x_train,y_train, epochs=20)

Epoch 1/20
4/4 [==============================] - 0s 3ms/step - loss: 0.8646 - accuracy: 0.7143
Epoch 2/20
4/4 [==============================] - 0s 3ms/step - loss: 0.8050 - accuracy: 0.9238
Epoch 3/20
4/4 [==============================] - 0s 3ms/step - loss: 0.7736 - accuracy: 0.7429
Epoch 4/20
4/4 [==============================] - 0s 5ms/step - loss: 0.7509 - accuracy: 0.6762
Epoch 5/20
4/4 [==============================] - 0s 5ms/step - loss: 0.7248 - accuracy: 0.6762
Epoch 6/20
4/4 [==============================] - 0s 3ms/step - loss: 0.7029 - accuracy: 0.6762
Epoch 7/20
4/4 [==============================] - 0s 3ms/step - loss: 0.6769 - accuracy: 0.6857
Epoch 8/20
4/4 [==============================] - 0s 4ms/step - loss: 0.6492 - accuracy: 0.7143
Epoch 9/20
4/4 [==============================] - 0s 4ms/step - loss: 0.6285 - accuracy: 0.8286
Epoch 10/20
4/4 [==============================] - 0s 4ms/step - loss: 0.6113 - accuracy: 0.9238
Epoch 11/20
4/4 [======================

In [ ]:
# Evaluate the Model
model.evaluate(x_test, y_test)

2/2 [==============================] - 0s 6ms/step - loss: 0.4942 - accuracy: 0.9333


[0.4942217469215393, 0.9333333373069763]

In [ ]:
# Predict for the first 10 Observations
pred=model.predict(x_test[:10])
print(pred)

[[0.06039979 0.39863217 0.540968  ]
 [0.07039084 0.48800835 0.44160083]
 [0.08478574 0.42752248 0.48769173]
 [0.08006471 0.4294576  0.4904777 ]
 [0.05393782 0.36945462 0.57660747]
 [0.10948895 0.44852477 0.4419863 ]
 [0.1050932  0.4446258  0.45028093]
 [0.83204114 0.09641193 0.07154684]
 [0.7257007  0.18266714 0.09163219]
 [0.04234989 0.42817044 0.5294797 ]]


In [ ]:
p=np.argmax(pred, axis=1)
print(p)
print(y_test[:10])

[2 1 2 2 2 1 2 0 0 2]
[2 1 2 2 2 1 1 0 0 2]


In [ ]:
# Prediction Result
for i in p:
  print("Predicted-Class: {},   Name: {}".format(i,z[i]))

Predicted-Class: 2,   Name: virginica
Predicted-Class: 1,   Name: versicolor
Predicted-Class: 2,   Name: virginica
Predicted-Class: 2,   Name: virginica
Predicted-Class: 2,   Name: virginica
Predicted-Class: 1,   Name: versicolor
Predicted-Class: 2,   Name: virginica
Predicted-Class: 0,   Name: setosa
Predicted-Class: 0,   Name: setosa
Predicted-Class: 2,   Name: virginica
